### ISSUE TITLE
Request: Sound Yaml cleanup

### ISSUE THREAD

**Issue by DangerRevolution** [Simple-Station/Einstein-Engines#743] opened 2024-08-17 07:32 UTC
# Description

- [x] #742
- [ ] more yaml items should have pick up & equip sounds
- [ ] yaml items need to be combed through to make sure they have sensible sounds, similar to #742

**Comment by DEATHB4DEFEAT** [comment] 2024-09-08 07:53
Duplicate of #474.

**Closed by DEATHB4DEFEAT** 2024-09-08 07:53 UTC
