### ISSUE TITLE
DeltaV tag in the main options menu

### ISSUE THREAD

**Issue by DangerRevolution** [Simple-Station/Einstein-Engines#494] opened 2024-06-29 18:13 UTC
# Description

Resources/Locale/en-US/deltav/escape-menu/options-menu.ftl

I want Goldfish crackers

# Media

![image](https://github.com/Simple-Station/Einstein-Engines/assets/142105406/0b60e1a7-f5d1-445b-b8ac-d23d9ca90e45)

**Comment by DEATHB4DEFEAT** [comment] 2024-07-27 08:33
guh, duplicate of https://github.com/Simple-Station/Einstein-Engines/issues/481, which you also made

**Closed by DEATHB4DEFEAT** 2024-07-27 08:33 UTC
Labels: Priority: 3-Medium, Size: 5-Very Small, Type: Bug, Type: Cleanup
